-- AppointmentSaaS - PostgreSQL schema, business rules, RLS and demo seed
-- Execute this file once in Supabase SQL Editor.

create extension if not exists pgcrypto;
create extension if not exists btree_gist;

-- ---------------------------------------------------------------------------
-- Core tables
-- ---------------------------------------------------------------------------

create table if not exists public.businesses (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  phone text,
  address text,
  timezone text not null default 'America/Santo_Domingo',
  subscription_plan text not null default 'Pro' check (subscription_plan in ('Básico','Pro')),
  trial_days integer not null default 30 check (trial_days >= 0),
  notification_immediate boolean not null default true,
  notification_24h boolean not null default true,
  notification_2h boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text,
  role text not null default 'client' check (role in ('admin','employee','client')),
  business_id uuid references public.businesses(id) on delete set null,
  staff_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  price numeric(10,2) not null check (price >= 0),
  duration_minutes integer not null check (duration_minutes between 5 and 720),
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, name)
);

create table if not exists public.staff (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  user_id uuid unique references auth.users(id) on delete set null,
  name text not null,
  specialty text not null default '',
  schedule_label text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, name)
);

alter table public.profiles
  drop constraint if exists profiles_staff_id_fkey;
alter table public.profiles
  add constraint profiles_staff_id_fkey foreign key (staff_id) references public.staff(id) on delete set null;

create table if not exists public.business_hours (
  business_id uuid not null references public.businesses(id) on delete cascade,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  is_open boolean not null default false,
  opening_time time not null default '09:00',
  closing_time time not null default '17:00',
  primary key (business_id, day_of_week),
  check (not is_open or opening_time < closing_time)
);

create table if not exists public.business_closures (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  closure_date date not null,
  reason text not null,
  created_at timestamptz not null default now(),
  unique (business_id, closure_date)
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  client_id uuid references auth.users(id) on delete set null,
  client_name text not null,
  client_phone text not null,
  client_email text not null,
  service_id bigint not null references public.services(id),
  staff_id bigint not null references public.staff(id),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  local_date date not null,
  local_time time not null,
  status text not null default 'Pendiente' check (status in ('Pendiente','Confirmada','Completada','Cancelada','No asistió')),
  source text not null default 'Cliente' check (source in ('Cliente','Negocio')),
  notes text not null default '',
  reminder_status text not null default 'Programado' check (reminder_status in ('Programado','Enviado','Cancelado','Error')),
  email_status text not null default 'Pendiente' check (email_status in ('Pendiente','Enviado','Error','No configurado')),
  email_sent_at timestamptz,
  confirmation_code text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

-- Prevent overlapping active appointments for the same professional.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'appointments_no_staff_overlap'
  ) then
    alter table public.appointments
      add constraint appointments_no_staff_overlap
      exclude using gist (
        staff_id with =,
        tstzrange(starts_at, ends_at, '[)') with &&
      )
      where (status not in ('Cancelada','No asistió'));
  end if;
end $$;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text not null default 'Sistema',
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists appointments_business_date_idx on public.appointments (business_id, local_date, local_time);
create index if not exists appointments_client_idx on public.appointments (client_id, starts_at);
create index if not exists appointments_staff_idx on public.appointments (staff_id, starts_at);
create index if not exists audit_logs_business_created_idx on public.audit_logs (business_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Timestamp helpers and profile provisioning
-- ---------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

 drop trigger if exists businesses_set_updated_at on public.businesses;
create trigger businesses_set_updated_at before update on public.businesses
for each row execute function public.set_updated_at();

 drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

 drop trigger if exists services_set_updated_at on public.services;
create trigger services_set_updated_at before update on public.services
for each row execute function public.set_updated_at();

 drop trigger if exists staff_set_updated_at on public.staff;
create trigger staff_set_updated_at before update on public.staff
for each row execute function public.set_updated_at();

 drop trigger if exists appointments_set_updated_at on public.appointments;
create trigger appointments_set_updated_at before update on public.appointments
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, phone, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.raw_user_meta_data ->> 'phone',
    'client'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

 drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Authorization helper functions
-- ---------------------------------------------------------------------------

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_business_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select business_id from public.profiles where id = auth.uid();
$$;

create or replace function public.is_business_admin(target_business uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and business_id = target_business
  );
$$;

create or replace function public.is_business_member(target_business uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin','employee') and business_id = target_business
  );
$$;

create or replace function public.is_assigned_employee(target_staff bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.staff
    where id = target_staff and user_id = auth.uid()
  );
$$;

create or replace function public.write_audit(target_business uuid, action_text text, actor_text text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (business_id, actor_id, actor_name, action)
  values (
    target_business,
    auth.uid(),
    coalesce(actor_text, (select full_name from public.profiles where id = auth.uid()), 'Sistema'),
    action_text
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.businesses enable row level security;
alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.staff enable row level security;
alter table public.business_hours enable row level security;
alter table public.business_closures enable row level security;
alter table public.appointments enable row level security;
alter table public.audit_logs enable row level security;

-- Public catalog data.
drop policy if exists businesses_public_read on public.businesses;
create policy businesses_public_read on public.businesses for select using (true);

drop policy if exists businesses_admin_update on public.businesses;
create policy businesses_admin_update on public.businesses for update
using (public.is_business_admin(id)) with check (public.is_business_admin(id));

drop policy if exists profiles_own_read on public.profiles;
create policy profiles_own_read on public.profiles for select using (id = auth.uid());

drop policy if exists profiles_admin_read on public.profiles;
create policy profiles_admin_read on public.profiles for select
using (public.is_business_admin(business_id));

drop policy if exists profiles_own_update on public.profiles;
-- Profile role/business changes are performed only by trusted administrative processes.

drop policy if exists services_public_read on public.services;
create policy services_public_read on public.services for select
using (active or public.is_business_member(business_id));

drop policy if exists services_admin_all on public.services;
create policy services_admin_all on public.services for all
using (public.is_business_admin(business_id)) with check (public.is_business_admin(business_id));

drop policy if exists staff_public_read on public.staff;
create policy staff_public_read on public.staff for select
using (active or public.is_business_member(business_id));

drop policy if exists staff_admin_all on public.staff;
create policy staff_admin_all on public.staff for all
using (public.is_business_admin(business_id)) with check (public.is_business_admin(business_id));

drop policy if exists hours_public_read on public.business_hours;
create policy hours_public_read on public.business_hours for select using (true);

drop policy if exists hours_admin_all on public.business_hours;
create policy hours_admin_all on public.business_hours for all
using (public.is_business_admin(business_id)) with check (public.is_business_admin(business_id));

drop policy if exists closures_public_read on public.business_closures;
create policy closures_public_read on public.business_closures for select using (true);

drop policy if exists closures_admin_all on public.business_closures;
create policy closures_admin_all on public.business_closures for all
using (public.is_business_admin(business_id)) with check (public.is_business_admin(business_id));

-- Appointments are created/changed through validated RPC functions. Direct reads
-- are restricted by role and ownership.
drop policy if exists appointments_client_read on public.appointments;
create policy appointments_client_read on public.appointments for select
using (client_id = auth.uid());

drop policy if exists appointments_admin_read on public.appointments;
create policy appointments_admin_read on public.appointments for select
using (public.is_business_admin(business_id));

drop policy if exists appointments_employee_read on public.appointments;
create policy appointments_employee_read on public.appointments for select
using (public.is_business_member(business_id) and public.current_profile_role() = 'employee' and public.is_assigned_employee(staff_id));

drop policy if exists audit_admin_read on public.audit_logs;
create policy audit_admin_read on public.audit_logs for select
using (public.is_business_admin(business_id));

-- Base privileges; RLS remains the authorization boundary.
grant usage on schema public to anon, authenticated;
grant select on public.businesses, public.services, public.staff, public.business_hours, public.business_closures to anon, authenticated;
grant select on public.profiles, public.appointments, public.audit_logs to authenticated;
grant insert, update, delete on public.businesses, public.services, public.staff, public.business_hours, public.business_closures to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ---------------------------------------------------------------------------
-- Validated appointment RPCs
-- ---------------------------------------------------------------------------

create or replace function public.book_appointment(
  p_business_slug text,
  p_service_id bigint,
  p_staff_id bigint,
  p_starts_at timestamptz,
  p_notes text default ''
)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_business public.businesses%rowtype;
  v_service public.services%rowtype;
  v_staff public.staff%rowtype;
  v_profile public.profiles%rowtype;
  v_email text;
  v_local_start timestamp;
  v_local_end timestamp;
  v_day smallint;
  v_hours public.business_hours%rowtype;
  v_ends_at timestamptz;
  v_code text;
  v_row public.appointments%rowtype;
begin
  if auth.uid() is null then
    raise exception 'Debes iniciar sesión para reservar.' using errcode = '42501';
  end if;

  select * into v_business from public.businesses where slug = p_business_slug;
  if not found then raise exception 'Negocio no encontrado.'; end if;

  select * into v_profile from public.profiles where id = auth.uid();
  select email into v_email from auth.users where id = auth.uid();

  select * into v_service from public.services
  where id = p_service_id and business_id = v_business.id and active;
  if not found then raise exception 'Servicio no disponible.'; end if;

  select * into v_staff from public.staff
  where id = p_staff_id and business_id = v_business.id and active;
  if not found then raise exception 'Profesional no disponible.'; end if;

  if p_starts_at <= now() then
    raise exception 'No se puede reservar una hora que ya pasó.';
  end if;

  v_ends_at := p_starts_at + make_interval(mins => v_service.duration_minutes);
  v_local_start := p_starts_at at time zone v_business.timezone;
  v_local_end := v_ends_at at time zone v_business.timezone;
  v_day := extract(dow from v_local_start)::smallint;

  if exists (
    select 1 from public.business_closures
    where business_id = v_business.id and closure_date = v_local_start::date
  ) then
    raise exception 'El negocio está cerrado en la fecha seleccionada.';
  end if;

  select * into v_hours from public.business_hours
  where business_id = v_business.id and day_of_week = v_day;

  if not found or not v_hours.is_open then
    raise exception 'El negocio no trabaja ese día.';
  end if;

  if v_local_start::time < v_hours.opening_time
     or v_local_end::date <> v_local_start::date
     or v_local_end::time > v_hours.closing_time then
    raise exception 'La cita queda fuera del horario del negocio.';
  end if;

  if exists (
    select 1 from public.appointments a
    where a.staff_id = p_staff_id
      and a.status not in ('Cancelada','No asistió')
      and tstzrange(a.starts_at, a.ends_at, '[)') && tstzrange(p_starts_at, v_ends_at, '[)')
  ) then
    raise exception 'El horario ya no está disponible.';
  end if;

  v_code := 'APT-' || upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 10));

  insert into public.appointments (
    business_id, client_id, client_name, client_phone, client_email,
    service_id, staff_id, starts_at, ends_at, local_date, local_time,
    status, source, notes, confirmation_code
  ) values (
    v_business.id, auth.uid(), coalesce(nullif(v_profile.full_name,''), split_part(v_email,'@',1)),
    coalesce(v_profile.phone,''), v_email, p_service_id, p_staff_id,
    p_starts_at, v_ends_at, v_local_start::date, v_local_start::time,
    'Confirmada', 'Cliente', coalesce(p_notes,''), v_code
  ) returning * into v_row;

  perform public.write_audit(v_business.id, 'Cita ' || v_code || ' creada desde el portal del cliente');
  return v_row;
exception
  when exclusion_violation then
    raise exception 'El horario acaba de ser ocupado. Selecciona otro.';
end;
$$;

create or replace function public.admin_create_appointment(
  p_service_id bigint,
  p_staff_id bigint,
  p_starts_at timestamptz,
  p_client_name text,
  p_client_phone text,
  p_client_email text,
  p_notes text default ''
)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_business public.businesses%rowtype;
  v_service public.services%rowtype;
  v_staff public.staff%rowtype;
  v_local_start timestamp;
  v_local_end timestamp;
  v_day smallint;
  v_hours public.business_hours%rowtype;
  v_ends_at timestamptz;
  v_code text;
  v_row public.appointments%rowtype;
begin
  select b.* into v_business from public.businesses b
  where b.id = public.current_business_id() and public.current_profile_role() = 'admin';
  if not found then raise exception 'Acceso administrativo requerido.' using errcode = '42501'; end if;

  select * into v_service from public.services where id=p_service_id and business_id=v_business.id and active;
  if not found then raise exception 'Servicio no disponible.'; end if;
  select * into v_staff from public.staff where id=p_staff_id and business_id=v_business.id and active;
  if not found then raise exception 'Profesional no disponible.'; end if;
  if p_starts_at <= now() then raise exception 'No se puede agendar en el pasado.'; end if;

  v_ends_at := p_starts_at + make_interval(mins => v_service.duration_minutes);
  v_local_start := p_starts_at at time zone v_business.timezone;
  v_local_end := v_ends_at at time zone v_business.timezone;
  v_day := extract(dow from v_local_start)::smallint;

  if exists (select 1 from public.business_closures where business_id=v_business.id and closure_date=v_local_start::date) then
    raise exception 'El negocio está cerrado en esa fecha.';
  end if;
  select * into v_hours from public.business_hours where business_id=v_business.id and day_of_week=v_day;
  if not found or not v_hours.is_open then raise exception 'El negocio no trabaja ese día.'; end if;
  if v_local_start::time < v_hours.opening_time or v_local_end::date<>v_local_start::date or v_local_end::time>v_hours.closing_time then
    raise exception 'La cita queda fuera del horario del negocio.';
  end if;
  if exists (
    select 1 from public.appointments a where a.staff_id=p_staff_id
      and a.status not in ('Cancelada','No asistió')
      and tstzrange(a.starts_at,a.ends_at,'[)') && tstzrange(p_starts_at,v_ends_at,'[)')
  ) then raise exception 'El profesional ya tiene una cita en ese horario.'; end if;

  v_code := 'APT-' || upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 10));
  insert into public.appointments (
    business_id, client_id, client_name, client_phone, client_email,
    service_id, staff_id, starts_at, ends_at, local_date, local_time,
    status, source, notes, confirmation_code
  ) values (
    v_business.id, null, trim(p_client_name), trim(p_client_phone), lower(trim(p_client_email)),
    p_service_id, p_staff_id, p_starts_at, v_ends_at, v_local_start::date, v_local_start::time,
    'Pendiente', 'Negocio', coalesce(p_notes,''), v_code
  ) returning * into v_row;

  perform public.write_audit(v_business.id, 'Cita ' || v_code || ' creada manualmente');
  return v_row;
exception
  when exclusion_violation then raise exception 'El horario acaba de ser ocupado.';
end;
$$;

create or replace function public.set_appointment_status(p_appointment_id bigint, p_status text)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.appointments%rowtype;
begin
  if p_status not in ('Pendiente','Confirmada','Completada','Cancelada','No asistió') then
    raise exception 'Estado inválido.';
  end if;

  select * into v_row from public.appointments where id=p_appointment_id;
  if not found then raise exception 'Cita no encontrada.'; end if;

  if not public.is_business_admin(v_row.business_id) and not public.is_assigned_employee(v_row.staff_id) then
    raise exception 'No tienes permiso para modificar esta cita.' using errcode='42501';
  end if;

  update public.appointments
  set status=p_status,
      reminder_status=case when p_status='Cancelada' then 'Cancelado' else reminder_status end
  where id=p_appointment_id returning * into v_row;

  perform public.write_audit(v_row.business_id, 'Cita ' || v_row.confirmation_code || ' actualizada a ' || p_status);
  return v_row;
end;
$$;

create or replace function public.cancel_my_appointment(p_appointment_id bigint)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.appointments%rowtype;
begin
  select * into v_row from public.appointments where id=p_appointment_id and client_id=auth.uid();
  if not found then raise exception 'Cita no encontrada.' using errcode='42501'; end if;
  if v_row.status in ('Cancelada','Completada','No asistió') then raise exception 'La cita ya no puede cancelarse.'; end if;
  if v_row.starts_at < now() + interval '2 hours' then raise exception 'La cancelación en línea requiere al menos 2 horas de anticipación.'; end if;

  update public.appointments set status='Cancelada', reminder_status='Cancelado'
  where id=p_appointment_id returning * into v_row;
  perform public.write_audit(v_row.business_id, 'Cita ' || v_row.confirmation_code || ' cancelada por el cliente');
  return v_row;
end;
$$;

create or replace function public.lookup_appointment_by_code(p_code text)
returns table (
  id bigint,
  confirmation_code text,
  status text,
  local_date date,
  local_time time,
  starts_at timestamptz,
  service_id bigint,
  service_name text,
  staff_id bigint,
  staff_name text,
  business_name text,
  business_phone text,
  business_address text
)
language sql
stable
security definer
set search_path = public
as $$
  select a.id, a.confirmation_code, a.status, a.local_date, a.local_time, a.starts_at,
         a.service_id, s.name, a.staff_id, st.name, b.name, b.phone, b.address
  from public.appointments a
  join public.services s on s.id=a.service_id
  join public.staff st on st.id=a.staff_id
  join public.businesses b on b.id=a.business_id
  where upper(a.confirmation_code)=upper(trim(p_code))
  limit 1;
$$;

create or replace function public.log_client_event(p_action text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_business uuid;
begin
  select business_id into v_business from public.profiles where id=auth.uid();
  if v_business is null then
    select id into v_business from public.businesses order by created_at limit 1;
  end if;
  if v_business is not null then perform public.write_audit(v_business,p_action); end if;
end;
$$;

-- Restrict internal helper functions from direct invocation.
revoke all on function public.write_audit(uuid,text,text) from public, anon, authenticated;
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;

-- Permissions for RPCs.
grant execute on function public.book_appointment(text,bigint,bigint,timestamptz,text) to authenticated;
grant execute on function public.admin_create_appointment(bigint,bigint,timestamptz,text,text,text,text) to authenticated;
grant execute on function public.set_appointment_status(bigint,text) to authenticated;
grant execute on function public.cancel_my_appointment(bigint) to authenticated;
grant execute on function public.lookup_appointment_by_code(text) to anon, authenticated;
grant execute on function public.log_client_event(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Demo business and catalog seed
-- ---------------------------------------------------------------------------

insert into public.businesses (
  id, slug, name, phone, address, timezone, subscription_plan, trial_days
) values (
  '11111111-1111-1111-1111-111111111111',
  'barberia-caribe',
  'Barbería Caribe',
  '809-555-0101',
  'Av. Winston Churchill, Santo Domingo',
  'America/Santo_Domingo',
  'Pro',
  17
) on conflict (slug) do update set
  name=excluded.name, phone=excluded.phone, address=excluded.address, timezone=excluded.timezone;

insert into public.services (id,business_id,name,price,duration_minutes,description,active) values
  (1,'11111111-1111-1111-1111-111111111111','Corte',700,30,'Corte clásico o moderno según preferencia.',true),
  (2,'11111111-1111-1111-1111-111111111111','Corte + Barba',1200,45,'Servicio completo de corte y arreglo de barba.',true),
  (3,'11111111-1111-1111-1111-111111111111','Spa Facial',1500,60,'Limpieza facial y cuidado básico de la piel.',true),
  (4,'11111111-1111-1111-1111-111111111111','Peinado',900,40,'Peinado y terminación profesional.',true)
on conflict (id) do update set
  name=excluded.name, price=excluded.price, duration_minutes=excluded.duration_minutes,
  description=excluded.description, active=excluded.active;

insert into public.staff (id,business_id,name,specialty,schedule_label,active) values
  (1,'11111111-1111-1111-1111-111111111111','Carlos','Barbero senior','Lun-Sáb',true),
  (2,'11111111-1111-1111-1111-111111111111','Miguel','Corte y barba','Mar-Sáb',true),
  (3,'11111111-1111-1111-1111-111111111111','Andrea','Estética y peinados','Lun-Vie',true)
on conflict (id) do update set
  name=excluded.name, specialty=excluded.specialty, schedule_label=excluded.schedule_label, active=excluded.active;

insert into public.business_hours (business_id,day_of_week,is_open,opening_time,closing_time) values
  ('11111111-1111-1111-1111-111111111111',0,false,'10:00','14:00'),
  ('11111111-1111-1111-1111-111111111111',1,true,'09:00','20:00'),
  ('11111111-1111-1111-1111-111111111111',2,true,'09:00','20:00'),
  ('11111111-1111-1111-1111-111111111111',3,true,'09:00','20:00'),
  ('11111111-1111-1111-1111-111111111111',4,true,'09:00','20:00'),
  ('11111111-1111-1111-1111-111111111111',5,true,'09:00','20:00'),
  ('11111111-1111-1111-1111-111111111111',6,true,'09:00','18:00')
on conflict (business_id,day_of_week) do update set
  is_open=excluded.is_open, opening_time=excluded.opening_time, closing_time=excluded.closing_time;

select setval(pg_get_serial_sequence('public.services','id'), greatest((select max(id) from public.services),1));
select setval(pg_get_serial_sequence('public.staff','id'), greatest((select max(id) from public.staff),1));
