-- AppointmentSaaS - directorio de clientes registrados y nuevos
-- Ejecutar después de 003_final_product_improvements.sql.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  profile_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  phone text not null default '',
  email text not null,
  active boolean not null default true,
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists clients_business_email_unique on public.clients (business_id, lower(email));
create index if not exists clients_business_name_idx on public.clients (business_id, full_name);

alter table public.appointments
  add column if not exists client_record_id bigint references public.clients(id) on delete set null;

create index if not exists appointments_client_record_idx on public.appointments (client_record_id, starts_at);

drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at before update on public.clients
for each row execute function public.set_updated_at();

alter table public.clients enable row level security;

drop policy if exists clients_admin_all on public.clients;
create policy clients_admin_all on public.clients for all
using (public.is_business_admin(business_id))
with check (public.is_business_admin(business_id));

drop policy if exists clients_employee_read on public.clients;
create policy clients_employee_read on public.clients for select
using (public.is_business_member(business_id) and public.current_profile_role()='employee');

drop policy if exists clients_own_read on public.clients;
create policy clients_own_read on public.clients for select using (profile_id=auth.uid());

grant select on public.clients to authenticated;
grant usage, select on sequence public.clients_id_seq to authenticated;

create or replace function public.ensure_business_client(
  p_business_id uuid,p_profile_id uuid,p_full_name text,p_phone text,p_email text
)
returns public.clients
language plpgsql
security definer
set search_path=pg_catalog,public
as $$
declare v_client public.clients%rowtype;v_email text:=lower(trim(p_email));
begin
  if trim(coalesce(p_full_name,''))='' then raise exception 'El nombre del cliente es obligatorio.';end if;
  if v_email='' then raise exception 'El correo del cliente es obligatorio.';end if;

  select * into v_client from public.clients
  where business_id=p_business_id and lower(email)=v_email limit 1;

  if found then
    update public.clients set
      profile_id=coalesce(profile_id,p_profile_id),
      full_name=trim(p_full_name),
      phone=trim(coalesce(p_phone,'')),
      email=v_email,
      active=true
    where id=v_client.id returning * into v_client;
  else
    insert into public.clients(business_id,profile_id,full_name,phone,email,active)
    values(p_business_id,p_profile_id,trim(p_full_name),trim(coalesce(p_phone,'')),v_email,true)
    returning * into v_client;
  end if;
  return v_client;
end;$$;

insert into public.clients(business_id,profile_id,full_name,phone,email,active)
select distinct on(a.business_id,lower(a.client_email))
  a.business_id,a.client_id,a.client_name,a.client_phone,lower(a.client_email),true
from public.appointments a
where trim(a.client_email)<>''
order by a.business_id,lower(a.client_email),a.created_at desc
on conflict do nothing;

update public.clients c set profile_id=u.id
from auth.users u where c.profile_id is null and lower(c.email)=lower(u.email);

update public.appointments a set client_record_id=c.id
from public.clients c
where a.client_record_id is null and c.business_id=a.business_id and lower(c.email)=lower(a.client_email);

create or replace function public.book_appointment(
  p_business_slug text,p_service_id bigint,p_staff_id bigint,p_starts_at timestamptz,p_notes text default ''
)
returns public.appointments language plpgsql security definer
set search_path=pg_catalog,public,extensions
as $$
declare
  v_business public.businesses%rowtype;v_service public.services%rowtype;v_staff public.staff%rowtype;
  v_profile public.profiles%rowtype;v_email text;v_client public.clients%rowtype;
  v_local_start timestamp;v_local_end timestamp;v_day smallint;v_hours public.business_hours%rowtype;
  v_ends_at timestamptz;v_code text;v_row public.appointments%rowtype;
begin
  if auth.uid() is null then raise exception 'Debes iniciar sesión para reservar.' using errcode='42501';end if;
  select * into v_business from public.businesses where slug=p_business_slug;if not found then raise exception 'Negocio no encontrado.';end if;
  select * into v_profile from public.profiles where id=auth.uid();
  select email into v_email from auth.users where id=auth.uid();
  select * into v_service from public.services where id=p_service_id and business_id=v_business.id and active;if not found then raise exception 'Servicio no disponible.';end if;
  select * into v_staff from public.staff where id=p_staff_id and business_id=v_business.id and active;if not found then raise exception 'Profesional no disponible.';end if;
  if p_starts_at<=now() then raise exception 'No se puede reservar una hora que ya pasó.';end if;
  v_ends_at:=p_starts_at+make_interval(mins=>v_service.duration_minutes);v_local_start:=p_starts_at at time zone v_business.timezone;v_local_end:=v_ends_at at time zone v_business.timezone;v_day:=extract(dow from v_local_start)::smallint;
  if exists(select 1 from public.business_closures where business_id=v_business.id and closure_date=v_local_start::date) then raise exception 'El negocio está cerrado en la fecha seleccionada.';end if;
  select * into v_hours from public.business_hours where business_id=v_business.id and day_of_week=v_day;
  if not found or not v_hours.is_open then raise exception 'El negocio no trabaja ese día.';end if;
  if v_local_start::time<v_hours.opening_time or v_local_end::date<>v_local_start::date or v_local_end::time>v_hours.closing_time then raise exception 'La cita queda fuera del horario del negocio.';end if;
  if exists(select 1 from public.appointments a where a.staff_id=p_staff_id and a.status not in('Cancelada','No asistió') and tstzrange(a.starts_at,a.ends_at,'[)')&&tstzrange(p_starts_at,v_ends_at,'[)')) then raise exception 'El horario ya no está disponible.';end if;
  v_client:=public.ensure_business_client(v_business.id,auth.uid(),coalesce(nullif(v_profile.full_name,''),split_part(v_email,'@',1)),coalesce(v_profile.phone,''),v_email);
  v_code:='APT-'||upper(substr(encode(extensions.gen_random_bytes(8),'hex'),1,10));
  insert into public.appointments(business_id,client_id,client_record_id,client_name,client_phone,client_email,service_id,staff_id,starts_at,ends_at,local_date,local_time,status,source,notes,confirmation_code)
  values(v_business.id,auth.uid(),v_client.id,v_client.full_name,v_client.phone,v_client.email,p_service_id,p_staff_id,p_starts_at,v_ends_at,v_local_start::date,v_local_start::time,'Confirmada','Cliente',coalesce(p_notes,''),v_code)
  returning * into v_row;
  perform public.write_audit(v_business.id,'Cita '||v_code||' creada desde el portal del cliente');return v_row;
exception when exclusion_violation then raise exception 'El horario acaba de ser ocupado. Selecciona otro.';end;$$;

create or replace function public.admin_create_appointment(
  p_service_id bigint,p_staff_id bigint,p_starts_at timestamptz,p_client_name text,p_client_phone text,p_client_email text,p_notes text default ''
)
returns public.appointments language plpgsql security definer
set search_path=pg_catalog,public,extensions
as $$
declare
  v_business public.businesses%rowtype;v_service public.services%rowtype;v_staff public.staff%rowtype;
  v_client public.clients%rowtype;v_profile_id uuid;v_local_start timestamp;v_local_end timestamp;
  v_day smallint;v_hours public.business_hours%rowtype;v_ends_at timestamptz;v_code text;v_row public.appointments%rowtype;
begin
  select b.* into v_business from public.businesses b where b.id=public.current_business_id() and public.current_profile_role()='admin';
  if not found then raise exception 'Acceso administrativo requerido.' using errcode='42501';end if;
  select * into v_service from public.services where id=p_service_id and business_id=v_business.id and active;if not found then raise exception 'Servicio no disponible.';end if;
  select * into v_staff from public.staff where id=p_staff_id and business_id=v_business.id and active;if not found then raise exception 'Profesional no disponible.';end if;
  if p_starts_at<=now() then raise exception 'No se puede agendar en el pasado.';end if;
  v_ends_at:=p_starts_at+make_interval(mins=>v_service.duration_minutes);v_local_start:=p_starts_at at time zone v_business.timezone;v_local_end:=v_ends_at at time zone v_business.timezone;v_day:=extract(dow from v_local_start)::smallint;
  if exists(select 1 from public.business_closures where business_id=v_business.id and closure_date=v_local_start::date) then raise exception 'El negocio está cerrado en esa fecha.';end if;
  select * into v_hours from public.business_hours where business_id=v_business.id and day_of_week=v_day;if not found or not v_hours.is_open then raise exception 'El negocio no trabaja ese día.';end if;
  if v_local_start::time<v_hours.opening_time or v_local_end::date<>v_local_start::date or v_local_end::time>v_hours.closing_time then raise exception 'La cita queda fuera del horario del negocio.';end if;
  if exists(select 1 from public.appointments a where a.staff_id=p_staff_id and a.status not in('Cancelada','No asistió') and tstzrange(a.starts_at,a.ends_at,'[)')&&tstzrange(p_starts_at,v_ends_at,'[)')) then raise exception 'El profesional ya tiene una cita en ese horario.';end if;
  select id into v_profile_id from auth.users where lower(email)=lower(trim(p_client_email)) limit 1;
  v_client:=public.ensure_business_client(v_business.id,v_profile_id,p_client_name,p_client_phone,p_client_email);
  v_code:='APT-'||upper(substr(encode(extensions.gen_random_bytes(8),'hex'),1,10));
  insert into public.appointments(business_id,client_id,client_record_id,client_name,client_phone,client_email,service_id,staff_id,starts_at,ends_at,local_date,local_time,status,source,notes,confirmation_code)
  values(v_business.id,v_profile_id,v_client.id,v_client.full_name,v_client.phone,v_client.email,p_service_id,p_staff_id,p_starts_at,v_ends_at,v_local_start::date,v_local_start::time,'Pendiente','Negocio',coalesce(p_notes,''),v_code)
  returning * into v_row;
  perform public.write_audit(v_business.id,'Cita '||v_code||' creada manualmente para '||v_client.full_name);return v_row;
exception when exclusion_violation then raise exception 'El horario acaba de ser ocupado.';end;$$;

create or replace function public.admin_create_historical_appointment(
  p_service_id bigint,p_staff_id bigint,p_starts_at timestamptz,p_client_name text,p_client_phone text,p_client_email text,p_status text,p_source text,p_notes text default ''
)
returns public.appointments language plpgsql security definer
set search_path=pg_catalog,public,extensions
as $$
declare
  v_business public.businesses%rowtype;v_service public.services%rowtype;v_staff public.staff%rowtype;
  v_client public.clients%rowtype;v_profile_id uuid;v_local_start timestamp;v_ends_at timestamptz;v_code text;v_row public.appointments%rowtype;
begin
  select b.* into v_business from public.businesses b where b.id=public.current_business_id() and public.current_profile_role()='admin';
  if not found then raise exception 'Acceso administrativo requerido.' using errcode='42501';end if;
  if p_starts_at>now() then raise exception 'El registro histórico debe pertenecer al pasado o al momento actual.';end if;
  if p_status not in('Completada','Cancelada','No asistió') then raise exception 'El historial requiere un estado final.';end if;
  if p_source not in('Cliente','Negocio') then raise exception 'Origen inválido.';end if;
  select * into v_service from public.services where id=p_service_id and business_id=v_business.id;if not found then raise exception 'Servicio no encontrado.';end if;
  select * into v_staff from public.staff where id=p_staff_id and business_id=v_business.id;if not found then raise exception 'Profesional no encontrado.';end if;
  select id into v_profile_id from auth.users where lower(email)=lower(trim(p_client_email)) limit 1;
  v_client:=public.ensure_business_client(v_business.id,v_profile_id,p_client_name,p_client_phone,p_client_email);
  v_ends_at:=p_starts_at+make_interval(mins=>v_service.duration_minutes);v_local_start:=p_starts_at at time zone v_business.timezone;v_code:='APT-H-'||upper(substr(encode(extensions.gen_random_bytes(8),'hex'),1,10));
  insert into public.appointments(business_id,client_id,client_record_id,client_name,client_phone,client_email,service_id,staff_id,starts_at,ends_at,local_date,local_time,status,source,notes,reminder_status,email_status,confirmation_code)
  values(v_business.id,v_profile_id,v_client.id,v_client.full_name,v_client.phone,v_client.email,p_service_id,p_staff_id,p_starts_at,v_ends_at,v_local_start::date,v_local_start::time,p_status,p_source,coalesce(p_notes,''),case when p_status='Cancelada' then 'Cancelado' else 'Enviado' end,'No configurado',v_code)
  returning * into v_row;
  perform public.write_audit(v_business.id,'Registro histórico '||v_code||' agregado para '||v_client.full_name);return v_row;
exception when exclusion_violation then raise exception 'El profesional ya posee un registro que coincide con ese horario.';end;$$;

grant execute on function public.book_appointment(text,bigint,bigint,timestamptz,text) to authenticated;
grant execute on function public.admin_create_appointment(bigint,bigint,timestamptz,text,text,text,text) to authenticated;
grant execute on function public.admin_create_historical_appointment(bigint,bigint,timestamptz,text,text,text,text,text,text) to authenticated;
